%Hi David
%I pulled out the main tractography commands from my pipeline and am
%pasting them here
% If you would like to step trough the entire pipeline, the
% "babyFatWrapper_fina.m would be the best place to start

    % Create per tissue response function estimation
    if (~computed.('wmResponseDhollander'))
        cmd_str = ['dwi2response dhollander -force ' ...
            files.dwi ' ' ...
            files.wmResponseDhollander  ' ' ...
            files.gmResponseDhollander  ' ' ...
            files.csfResponseDhollander ' ' ...
            '-mask ' files.brainmask ' ' ...
            '-grad ' files.b  ' ' ...
            '-voxels ' files.voxelsDhollander ' ' ...
            '-fa 0.1'];
        [status,results] = AFQ_mrtrix_cmd(cmd_str, 0, 1, mrtrixVersion);
    end
    
    
    % Compute the CSD estimates:
        if (~computed.('wmCsdMSMTDhollander'))   && (mrtrixVersion > 2)
        cmd_str = ['dwi2fod msmt_csd ' ...
            files.dwi ' ' ...
            files.wmResponseDhollander  ' '  files.wmCsdMSMTDhollander ' '  ...
            files.csfResponseDhollander ' '  files.csfCsdMSMTDhollander ' '  ...
            '-mask ' files.brainmask ' ' ...
            '-grad ' files.b ' ' ...
            '-force'];
        
        [status,results] = AFQ_mrtrix_cmd(cmd_str, 0, 1,mrtrixVersion);
        end
        
   %run tractography
    %algo: IFOD1
    %angle: 15
    %select: 2000000
    %cutoff: 0.05
           cmd_str = ['tckgen ' csdFile ' ' ...
            '-algo ' algo ' ' ...
            '-backtrack -crop_at_gmwmi -info ' ...
            '-seed_gmwmi ' gmwmi ' ' ...
            '-act ' file5tt ' ' ...
            '-angle ' num2str(angleValues(na)) ' ' ...
            '-select ' num2str(nSeeds) ' ' ...
            fgFileNameWithDir{na} ' ' ...
            '-cutoff ' num2str(cutoff) ' '...
            '-force'];
        
       
        